# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = ""
py_version = "3.7"
version = "0.1.0"


[tool.pyflow.scripts]


[tool.pyflow.dependencies]
requests = "^2.23.0"


[tool.pyflow.dev-dependencies]

